import './tsconfig-no-unchecked-side-effect-imports.test.ts'
import './tsconfig-force-consistent-casing-in-file-names.test.ts'
import './tsconfig-strict.test.ts'
import './tsconfig-assume-changes-only-affect-direct-dependencies.test.ts'
import './tsconfig-exact-optional-property-types.test.ts'
import './tsconfig-dont-skip-libcheck.test.ts'
