import './no-direct-click.test.ts'
import './no-lazy-nth-variable-name.test.ts'
import './no-inline-locator-in-expect.test.ts'
import './no-inline-nth-in-expect.test.ts'
import './prefer-import-meta-resolve.test.ts'
