import './no-direct-click.test.ts'
import './no-lazy-nth-variable-name.test.ts'
import './no-inline-locator-in-expect.test.ts'
import './no-inline-nth-in-expect.test.ts'
import './prefer-direct-api-destructuring.test.ts'
import './prefer-execute-extension-command.test.ts'
import './prefer-filesystem-set-files.test.ts'
import './prefer-import-meta-resolve.test.ts'
